# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with packages for kis3 configurations
Name: jolla-configuration-kis3
Requires:
- pattern:jolla-hw-adaptation-kis3
- pattern:jolla-sailfish-applications
- pattern:jolla-ui-wayland
# Early stages of porting benefit from these:
- pattern:sailfish-porter-tools

# Pre-installed applications, since we don't support OTA well enough:
- sailfish-office
- jolla-calculator
- jolla-email
- jolla-notes
- jolla-clock
- jolla-mediaplayer
- jolla-calendar
- sailfish-weather

Summary: Jolla Configuration kis3

